# Generated by Django 4.2.1 on 2023-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('pin', models.IntegerField()),
                ('incharge', models.CharField(max_length=300)),
                ('incharge_phone', models.CharField(max_length=300)),
                ('created_date', models.DateField(null=True)),
                ('ending_date', models.DateField(null=True)),
            ],
        ),
    ]
