# Generated by Django 4.2.1 on 2023-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('center_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dose_name', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('contacts', models.CharField(max_length=300)),
                ('id_proof_type', models.CharField(max_length=300)),
                ('id_proof_number', models.CharField(max_length=300)),
                ('slot_date', models.DateField(null=True)),
                ('slot_time', models.CharField(max_length=300)),
            ],
        ),
    ]
