# Generated by Django 4.2.1 on 2023-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbook',
            name='approved',
            field=models.CharField(default='no', max_length=300),
            preserve_default=False,
        ),
    ]
